# Detect Identical Samples from Punic Paper in imputed data
Works only for high enough coverage

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import socket as socket
import os as os
import sys as sys
import multiprocessing as mp
import h5py
import allel
import itertools as it
socket_name = socket.gethostname()
print(socket_name)

if socket_name.startswith("compute-"):
    print("HSM O2 Computational partition detected.")
    path = "/n/groups/reich/hringbauer/git/hapBLOCK/"  # The Path on Harvard Cluster
else: 
    raise RuntimeWarning("Not compatible machine. Check!!")

os.chdir(path)  # Set the right Path (in line with Atom default)
print(os.getcwd())
print(f"CPU Count: {mp.cpu_count()}")

sys.path.insert(0,"/n/groups/reich/hringbauer/git/hapBLOCK/package/")  # hack to get development package first in path
from ancIBD.IO.h5_duplicates import get_match_df

compute-e-16-229.o2.rc.hms.harvard.edu
HSM O2 Computational partition detected.
/n/groups/reich/hringbauer/git/hapBLOCK
CPU Count: 28

### 1) Get IIDs to run

In [2]:
df_pun = pd.read_csv("/n/groups/reich/hringbauer/git/punic_aDNA/data/cluster_assignments_punic.v54.1.tsv", sep="\t") #./data/cluster_assignments_punic.v49.2.tsv
df_pun = df_pun[df_pun["label"].str.contains("Punic")].copy()
iids = df_pun["iid"].values
print(f"Loaded {len(iids)} IIDs")
df_pun["location"].value_counts()

Loaded 138 IIDs

Kerkouene     27
Carthage      17
Tharros       14
Akhziv        13
Birgi          9
Cap Bon        8
Eivissa        8
Villaricos     8
Motya          7
Malaga         7
Lilybaeum      7
Villamar       6
Selinunte      3
Cadiz          2
MonteSirai     2
Name: location, dtype: int64

## 2) Detect Identical

In [3]:
%%time
dft = get_match_df(ch=3, iids=iids[:10])

CPU times: user 3.75 s, sys: 123 ms, total: 3.88 s
Wall time: 3.9 s

## 3) Browse Output

In [4]:
dft2 = dft[dft["frac_snps"]>0.5]
dft2.sort_values(by="frac_match", ascending=False)[:50]

      iid1    iid2  frac_match  frac_snps
3   I12666  I24675    0.674885   0.740474
34  I24675   I4800    0.668762   0.717693
24  I24676  I24675    0.666492   0.692727
17  I24678  I24676    0.665436   0.728489
1   I12666  I24678    0.665117   0.781692
18  I24678  I24675    0.663668   0.724274
30  I24675  I24556    0.663493   0.737268
2   I12666  I24676    0.662594   0.744883
20  I24678  I22095    0.661487   0.782972
32  I24675   I4798    0.660745   0.763385
29  I24676   I4800    0.659714   0.720305
31  I24675  I22095    0.659140   0.742647
23  I24678   I4800    0.658353   0.758873
19  I24678  I24556    0.657343   0.780710
5   I12666  I22095    0.657055   0.806180
8   I12666   I4800    0.655993   0.781292
13  I12847  I22095    0.654959   0.816084
0   I12666  I12847    0.654532   0.817920
27  I24676   I4798    0.653024   0.768272
11  I12847  I24675    0.651900   0.747443
25  I24676  I24556    0.651340   0.742905
9   I12847  I24678    0.650839   0.790161
43   I4798   I4800    0.650609   0.805443
33  I24675   I4799    0.650320   0.768505
38  I24556   I4800    0.649691   0.775060
22  I24678   I4799    0.649101   0.814287
35  I24556  I22095    0.648834   0.802586
4   I12666  I24556    0.647106   0.804189
12  I12847  I24556    0.647058   0.811222
28  I24676   I4799    0.646257   0.773276
10  I12847  I24676    0.646245   0.751904
26  I24676  I22095    0.645950   0.745982
6   I12666   I4798    0.645017   0.838865
16  I12847   I4800    0.644736   0.787032
40  I22095   I4799    0.642678   0.840067
36  I24556   I4798    0.642043   0.830991
44   I4799   I4800    0.641918   0.811817
21  I24678   I4798    0.641788   0.807951
7   I12666   I4799    0.641275   0.846260
39  I22095   I4798    0.640206   0.833577
14  I12847   I4798    0.639468   0.844567
37  I24556   I4799    0.637670   0.838555
15  I12847   I4799    0.636785   0.851639
41  I22095   I4800    0.636642   0.777400
42   I4798   I4799    0.632532   0.874575